### ISSUE TITLE
ImportError: cannot import name custom_layers

### ISSUE THREAD

**Issue by wang-tf** [AimeeKing/crnn-tensorflow#2]
When I was trying `train_mjsyth.py`, it shows that:  
```
Traceback (most recent call last):
  File "train_mjsyth.py", line 8, in <module>
    from net import model
  File "/disk/data0/users/tengfei5/test/crnn-tensorflow/net/model.py", line 5, in <module>
    from net import custom_layers
ImportError: cannot import name custom_layers
```
Is there any file I didn't include ?

**Comment by wang-tf** [comment]
Then I copy a file form [ssd-tensorflow/nets/custom_layers.py](https://github.com/balancap/SSD-Tensorflow/blob/master/nets/custom_layers.py)  
While, I have new problems:
```
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Name: <unknown>, Feature: label/length (data type: int64) is required but could not be found.
	 [[Node: input/ParseSingleExample/ParseExample/ParseExample = ParseExample[Ndense=3, Nsparse=1, Tdense=[DT_STRING, DT_STRING, DT_INT64], dense_shapes=[[], [], [1]], sparse_types=[DT_INT64], _device="/job:localhost/replica:0/task:0/cpu:0"](input/ParseSingleExample/ExpandDims, input/ParseSingleExample/ParseExample/ParseExample/names, input/ParseSingleExample/ParseExample/ParseExample/sparse_keys_0, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_0, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_1, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_2, input/ParseSingleExample/ParseExample/Reshape, input/ParseSingleExample/ParseExample/Reshape_1, input/ParseSingleExample/ParseExample/Const)]]

Caused by op u'input/ParseSingleExample/ParseExample/ParseExample', defined at:
  File "train_mjsyth.py", line 105, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_mjsyth.py", line 44, in main
    num_epochs=num_epochs)
  File "/disk/data0/users/tengfei5/test/crnn-tensorflow/dataset/read_utils.py", line 34, in inputs
    img, label, length = read_and_decode(filename, num_epochs)
  File "/disk/data0/users/tengfei5/test/crnn-tensorflow/dataset/read_utils.py", line 16, in read_and_decode
    'label/length': tf.FixedLenFeature([1], tf.int64)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/parsing_ops.py", line 739, in parse_single_example
    dense_types, dense_defaults, dense_shapes, name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/parsing_ops.py", line 813, in _parse_single_example_raw
    name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/parsing_ops.py", line 688, in _parse_example_raw
    name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gen_parsing_ops.py", line 178, in _parse_example
    dense_shapes=dense_shapes, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Name: <unknown>, Feature: label/length (data type: int64) is required but could not be found.
	 [[Node: input/ParseSingleExample/ParseExample/ParseExample = ParseExample[Ndense=3, Nsparse=1, Tdense=[DT_STRING, DT_STRING, DT_INT64], dense_shapes=[[], [], [1]], sparse_types=[DT_INT64], _device="/job:localhost/replica:0/task:0/cpu:0"](input/ParseSingleExample/ExpandDims, input/ParseSingleExample/ParseExample/ParseExample/names, input/ParseSingleExample/ParseExample/ParseExample/sparse_keys_0, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_0, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_1, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_2, input/ParseSingleExample/ParseExample/Reshape, input/ParseSingleExample/ParseExample/Reshape_1, input/ParseSingleExample/ParseExample/Const)]]

2017-07-14 12:24:11.369512: W tensorflow/core/framework/op_kernel.cc:1152] Out of range: RandomShuffleQueue '_2_input/shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: input/shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT64, DT_INT64], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input/shuffle_batch/random_shuffle_queue, input/shuffle_batch/n)]]
2017-07-14 12:24:11.369599: W tensorflow/core/framework/op_kernel.cc:1152] Out of range: RandomShuffleQueue '_2_input/shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: input/shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT64, DT_INT64], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input/shuffle_batch/random_shuffle_queue, input/shuffle_batch/n)]]
2017-07-14 12:24:11.369624: W tensorflow/core/framework/op_kernel.cc:1152] Out of range: RandomShuffleQueue '_2_input/shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: input/shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT64, DT_INT64], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input/shuffle_batch/random_shuffle_queue, input/shuffle_batch/n)]]
2017-07-14 12:24:11.369940: W tensorflow/core/framework/op_kernel.cc:1152] Out of range: RandomShuffleQueue '_2_input/shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: input/shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT64, DT_INT64], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input/shuffle_batch/random_shuffle_queue, input/shuffle_batch/n)]]
2017-07-14 12:24:11.370040: W tensorflow/core/framework/op_kernel.cc:1152] Out of range: RandomShuffleQueue '_2_input/shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: input/shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT64, DT_INT64], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input/shuffle_batch/random_shuffle_queue, input/shuffle_batch/n)]]
2017-07-14 12:24:11.370094: W tensorflow/core/framework/op_kernel.cc:1152] Out of range: RandomShuffleQueue '_2_input/shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: input/shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT64, DT_INT64], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input/shuffle_batch/random_shuffle_queue, input/shuffle_batch/n)]]
2017-07-14 12:24:11.370144: W tensorflow/core/framework/op_kernel.cc:1152] Out of range: RandomShuffleQueue '_2_input/shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: input/shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT64, DT_INT64], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input/shuffle_batch/random_shuffle_queue, input/shuffle_batch/n)]]
2017-07-14 12:24:11.370257: W tensorflow/core/framework/op_kernel.cc:1152] Out of range: RandomShuffleQueue '_2_input/shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: input/shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT64, DT_INT64], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input/shuffle_batch/random_shuffle_queue, input/shuffle_batch/n)]]
2017-07-14 12:24:11.370335: W tensorflow/core/framework/op_kernel.cc:1152] Out of range: RandomShuffleQueue '_2_input/shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: input/shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT64, DT_INT64], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input/shuffle_batch/random_shuffle_queue, input/shuffle_batch/n)]]
Traceback (most recent call last):
  File "train_mjsyth.py", line 105, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_mjsyth.py", line 96, in main
    print('Done training for %d epochs, %d steps.' % (num_epochs, step))
TypeError: %d format: a number is required, not Variable
```
How can I fix it ? Thanks

**Comment by zoe218** [comment]
@wang-tf have you solved this question?

**Comment by novioleo** [comment]
@wang-tf @zoe218 find all in https://github.com/AimeeKing/my_practice_on_textbox

**Comment by ghost** [comment]
@novioleo@wang-tf @zoe218   can you run train_mjsyth.py ,  when i run it ,error reported.

**Comment by wang-tf** [comment]
Yes,  I can run it now. This problem is fixed if I use `num_epochs = None`. So actually it's not a problem. It just represent the train finished.

**Comment by ghost** [comment]
@wang-tf  if set num_epochs = None  ,The program has been stuck, no result....What's the matter？    thank you

**Comment by novioleo** [comment]
全部都是中国人，你们都贴图吧。好交流点。

**Comment by songwendong** [comment]
@novioleo  我设置num_epochs = None  然后程序就卡主了，也不出结果，  请问你们的程序能工作吗？训练有效果吗？

**Comment by novioleo** [comment]
@songwendong num_epochs作者在定义的时候是for循环里面的，可能有点问题，你debug一下试试～

**Comment by songwendong** [comment]
@songwendong  总体上来说这个代码是能工作的吧？改改 能用吧？我之前自己写的，没效果。。。浪费好多时间

**Comment by songwendong** [comment]
@wang-tf   设置num_epochs = None 然后程序就卡主了，请问你的能正常训练吗

**Comment by songwendong** [comment]
各种报错啊 。。。@novioleo  大神， 求救，他这个网络都跑不通啊

2017-08-01 17:37:37.662178: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\kernels\queue_base.cc:302] _1_input/shuffle_batch/random_shuffle_queue: Skipping cancelled dequeue attempt with queue not closed
Traceback (most recent call last):
  File "C:\soft\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1039, in _do_call
    return fn(*args)
  File "C:\soft\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _run_fn
    status, run_metadata)
  File "C:\soft\Anaconda3\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\soft\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [Expected shape for Tensor RCNN_net/sequence_length:0 is ] [1] [ but saw shape: ] [2]
	 [[Node: RCNN_net/rnn/Assert/Assert = Assert[T=[DT_STRING, DT_INT32, DT_STRING, DT_INT32], summarize=3, _device="/job:localhost/replica:0/task:0/cpu:0"](RCNN_net/rnn/All/_25, RCNN_net/rnn/Assert/Assert/data_0, RCNN_net/rnn/stack/_27, RCNN_net/rnn/Assert/Assert/data_2, RCNN_net/rnn/Shape_1/_29)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/songwendong/Desktop/pycode/fromtfrecord/detectnet.py", line 93, in <module>
  File "C:\soft\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "C:/Users/songwendong/Desktop/pycode/fromtfrecord/detectnet.py", line 82, in main
    
  File "C:\soft\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 778, in run
    run_metadata_ptr)
  File "C:\soft\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "C:\soft\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "C:\soft\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [Expected shape for Tensor RCNN_net/sequence_length:0 is ] [1] [ but saw shape: ] [2]
	 [[Node: RCNN_net/rnn/Assert/Assert = Assert[T=[DT_STRING, DT_INT32, DT_STRING, DT_INT32], summarize=3, _device="/job:localhost/replica:0/task:0/cpu:0"](RCNN_net/rnn/All/_25, RCNN_net/rnn/Assert/Assert/data_0, RCNN_net/rnn/stack/_27, RCNN_net/rnn/Assert/Assert/data_2, RCNN_net/rnn/Shape_1/_29)]]

Caused by op 'RCNN_net/rnn/Assert/Assert', defined at:
  File "C:/Users/songwendong/Desktop/pycode/fromtfrecord/detectnet.py", line 93, in <module>
  File "C:\soft\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "C:/Users/songwendong/Desktop/pycode/fromtfrecord/detectnet.py", line 47, in main
    logits, inputs, seq_len, W, b = crnn.net(sh_images)
  File "C:\Users\songwendong\Desktop\pycode\fromtfrecord\net\model.py", line 163, in net
    return BLSTM(net,self.params.nh,2,seq_len,self.params.nclass)
  File "C:\Users\songwendong\Desktop\pycode\fromtfrecord\net\model.py", line 78, in BLSTM
    outputs, _ = tf.nn.dynamic_rnn(cell, inputs, sequence_length=seq_len, dtype=tf.float32)#seq_len
  File "C:\soft\Anaconda3\lib\site-packages\tensorflow\python\ops\rnn.py", line 540, in dynamic_rnn
    [_assert_has_shape(sequence_length, [batch_size])]):
  File "C:\soft\Anaconda3\lib\site-packages\tensorflow\python\ops\rnn.py", line 535, in _assert_has_shape
    packed_shape, " but saw shape: ", x_shape])
  File "C:\soft\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 121, in Assert
    condition, data, summarize, name="Assert")
  File "C:\soft\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_logging_ops.py", line 39, in _assert
    summarize=summarize, name=name)
  File "C:\soft\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "C:\soft\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\soft\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): assertion failed: [Expected shape for Tensor RCNN_net/sequence_length:0 is ] [1] [ but saw shape: ] [2]
	 [[Node: RCNN_net/rnn/Assert/Assert = Assert[T=[DT_STRING, DT_INT32, DT_STRING, DT_INT32], summarize=3, _device="/job:localhost/replica:0/task:0/cpu:0"](RCNN_net/rnn/All/_25, RCNN_net/rnn/Assert/Assert/data_0, RCNN_net/rnn/stack/_27, RCNN_net/rnn/Assert/Assert/data_2, RCNN_net/rnn/Shape_1/_29)]]


Process finished with exit code 1

**Comment by novioleo** [comment]
@songwendong 
InvalidArgumentError (see above for traceback): assertion failed: [Expected shape for Tensor RCNN_net/sequence_length:0 is ] [1] [ but saw shape: ] [2]  你数据shape不对~你debug看下？

**Comment by songwendong** [comment]
@novioleo 万分感谢 ，他这程序根本运行不了

**Comment by novioleo** [comment]
@songwendong 那你要不要试试原版程序？https://github.com/weinman/cnn_lstm_ctc_ocr

**Comment by ghost** [comment]
@novioleo   多谢多谢

**Comment by novioleo** [comment]
就在github吧。平时不用其他的。
